version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "dockerize -wait tcp://mysql:3306 -timeout 20s /usr/deploy/scripts/start"
    container_name: app
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
      - mailcatcher
    environment:
      - ENABLE_SCHEDULE=true
      - ENABLE_WORKER=true
      - ENABLE_HORIZON=false
      - ENABLE_WEBSOCKETS=false
      - ENABLE_SUPERVISOR_GUI=true
      - SUPERVISORD_USER=admin
      - SUPERVISORD_PASS=secret

    env_file:
      - .env

    volumes:
     - .:/usr/share/nginx/html
     - ./.docker/storage/app:/usr/share/nginx/html/storage/app
     - ./.docker/storage/logs:/usr/share/nginx/html/storage/logs
    ports:
      - "8080:80"
      - "6001:6001"
      - "9001:9001"
    networks:
      - blueead

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./.docker/storage/mysql:/var/lib/mysql
    networks:
      - blueead

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./.docker/storage/redis:/data
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
    networks:
      - blueead

  mailcatcher:
    image: codions/mailcatcher
    container_name: mailcatcher
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - blueead

networks:
  blueead:
    driver: bridge
